apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sloth-release-name
  labels:
    helm.sh/chart: sloth-0.12.1
    app.kubernetes.io/managed-by: Helm
    app: sloth
    app.kubernetes.io/name: sloth
    app.kubernetes.io/instance: release-name
rules:
  - apiGroups: ["sloth.slok.dev"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["monitoring.coreos.com"]
    resources: ["prometheusrules"]
    verbs: ["create", "list", "get", "update", "watch"]