apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sloth-release-name
  labels:
    helm.sh/chart: sloth-0.12.1
    app.kubernetes.io/managed-by: Helm
    app: sloth
    app.kubernetes.io/name: sloth
    app.kubernetes.io/instance: release-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sloth-release-name
subjects:
  - kind: ServiceAccount
    name: sloth-release-name
    namespace: default