apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sloth-release-name
  namespace: default
  labels:
    helm.sh/chart: sloth-0.12.1
    app.kubernetes.io/managed-by: Helm
    app: sloth
    app.kubernetes.io/name: sloth
    app.kubernetes.io/instance: release-name
spec:
  selector:
    matchLabels:
      app: sloth
      app.kubernetes.io/name: sloth
      app.kubernetes.io/instance: release-name
  podMetricsEndpoints:
    - port: metrics