---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sloth
  namespace: argocd
spec:
  project: pruebas
  sources:
   - repoURL: https://slok.github.io/sloth
     targetRevision: 0.12.1
     chart: sloth
     helm:
       releaseName: sloth
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    # Prune Last (i.e. after it was synced) to not removed dynamically created admissions/patch jobs/pods
    - PruneLast=true